export const emptyCardInfo = [
  {
    id: 0,
    title: 'History of Georgia',
    subtitle: 'History of Georgia',
    numberOfQ: 20,
    time: 15,
    lng: 'en',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 1,
    title: 'Law basics',
    subtitle: 'Law basics',
    numberOfQ: 20,
    time: 15,
    lng: 'en',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 2,
    title: 'Georgian language',
    subtitle: 'Georgian language',
    numberOfQ: 20,
    time: 15,
    lng: 'en',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 3,
    title: 'History of Georgia',
    subtitle: 'History of Georgia',
    numberOfQ: 202,
    time: 60,
    lng: 'en',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 4,
    title: 'Law basics',
    subtitle: 'Law basics',
    numberOfQ: 200,
    time: 60,
    lng: 'en',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 5,
    title: 'Georgian language',
    subtitle: 'Georgian language',
    numberOfQ: 209,
    time: 60,
    lng: 'en',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 0,
    title: 'ისტორიიდან',
    subtitle: 'ისტორია',
    numberOfQ: 20,
    time: 15,
    lng: 'ge',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 1,
    title: 'კანონიდან',
    subtitle: 'კანონი',
    numberOfQ: 20,
    time: 15,
    lng: 'ge',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 2,
    title: 'ქართული ენიდან',
    subtitle: 'ქართული ენა',
    numberOfQ: 20,
    time: 15,
    lng: 'ge',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 3,
    title: 'ისტორიიდან',
    subtitle: 'ისტორია',
    numberOfQ: 202,
    time: 60,
    lng: 'ge',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 4,
    title: 'კანონიდან',
    subtitle: 'კანონი',
    numberOfQ: 200,
    time: 60,
    lng: 'ge',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 5,
    title: 'ქართული ენიდან',
    subtitle: 'ქართული ენა',
    numberOfQ: 209,
    time: 60,
    lng: 'ge',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 0,
    title: 'Истории Грузии',
    subtitle: 'История',
    numberOfQ: 20,
    time: 15,
    lng: 'ru',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 1,
    title: 'Праву',
    subtitle: 'Основы Права',
    numberOfQ: 20,
    time: 15,
    lng: 'ru',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 2,
    title: 'Грузинскому языку',
    subtitle: 'Грузинский язык',
    numberOfQ: 20,
    time: 15,
    lng: 'ru',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 3,
    title: 'Истории Грузии',
    subtitle: 'История',
    numberOfQ: 202,
    time: 60,
    lng: 'ru',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 4,
    title: 'Праву',
    subtitle: 'Основы Права',
    numberOfQ: 200,
    time: 60,
    lng: 'ru',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 5,
    title: 'Грузинскому языку',
    subtitle: 'Грузинский язык',
    numberOfQ: 209,
    time: 60,
    lng: 'ru',
    type: 2,
    navTitle: 'lang',
  },
];
