export const emptyCardInfo = [
  {
    id: 0,
    title: 'History',
    subtitle: 'History',
    numberOfQ: 20,
    time: 15,
    lng: 'en',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 1,
    title: 'Law',
    subtitle: 'Law',
    numberOfQ: 20,
    time: 15,
    lng: 'en',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 2,
    title: 'Language',
    subtitle: 'Language',
    numberOfQ: 20,
    time: 15,
    lng: 'en',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 3,
    title: 'History',
    subtitle: 'History',
    numberOfQ: 200,
    time: 60,
    lng: 'en',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 4,
    title: 'Law',
    subtitle: 'Law',
    numberOfQ: 200,
    time: 60,
    lng: 'en',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 5,
    title: 'Language',
    subtitle: 'Language',
    numberOfQ: 200,
    time: 60,
    lng: 'en',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 0,
    title: 'ისტორიიდან',
    subtitle: 'ისტორია',
    numberOfQ: 20,
    time: 15,
    lng: 'ge',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 1,
    title: 'კანონიდან',
    subtitle: 'კანონი',
    numberOfQ: 20,
    time: 15,
    lng: 'ge',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 2,
    title: 'ქართული ენიდან',
    subtitle: 'ქართული ენა',
    numberOfQ: 20,
    time: 15,
    lng: 'ge',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 3,
    title: 'ისტორიიდან',
    subtitle: 'ისტორია',
    numberOfQ: 200,
    time: 60,
    lng: 'ge',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 4,
    title: 'კანონიდან',
    subtitle: 'კანონი',
    numberOfQ: 200,
    time: 60,
    lng: 'ge',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 5,
    title: 'ქართული ენიდან',
    subtitle: 'ქართული ენა',
    numberOfQ: 200,
    time: 60,
    lng: 'ge',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 0,
    title: 'Истории',
    subtitle: 'История',
    numberOfQ: 20,
    time: 15,
    lng: 'ru',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 1,
    title: 'Закону',
    subtitle: 'Закон',
    numberOfQ: 20,
    time: 15,
    lng: 'ru',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 2,
    title: 'Грузинскому языку',
    subtitle: 'Грузинский язык',
    numberOfQ: 20,
    time: 15,
    lng: 'ru',
    type: 2,
    navTitle: 'lang',
  },
  {
    id: 3,
    title: 'Истории',
    subtitle: 'История',
    numberOfQ: 200,
    time: 60,
    lng: 'ru',
    type: 0,
    navTitle: 'hist',
  },
  {
    id: 4,
    title: 'Закону',
    subtitle: 'Закон',
    numberOfQ: 200,
    time: 60,
    lng: 'ru',
    type: 1,
    navTitle: 'law',
  },
  {
    id: 5,
    title: 'Грузинскому языку',
    subtitle: 'Грузинский язык',
    numberOfQ: 200,
    time: 60,
    lng: 'ru',
    type: 2,
    navTitle: 'lang',
  },
];
